/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JoplinMenu: typeof import('./src/components/JoplinMenu.vue')['default']
    JoplinPage: typeof import('./src/components/JoplinPage.vue')['default']
    JoplinRecursiveList: typeof import('./src/components/JoplinRecursiveList.vue')['default']
    JoplinSubList: typeof import('./src/components/JoplinSubList.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
  }
}
